### ISSUE TITLE
Missing subscription due to race condition 

### ISSUE THREAD

**Issue by ch-k** [pytroll/posttroll#5]
When starting publishers and subscribers at the same time, occasionally a processes is not able to subscibe to topics.

Example (Trollduction):
- 1x trollstalker, 3x l2processors started at the same time via supervisor.
- only 2 l2processors receive messages of trollstalker

A delay before subscribing should avoid this error. Unfortunatly, supervisor does not support this out-of-the-box: [supervisord Starts All Processes at the Same Time](https://github.com/Supervisor/supervisor/issues/122)

Log files:
[log-21102016-l2proc01-refuses-to-work.zip](https://github.com/pytroll/posttroll/files/547658/log-21102016-l2proc01-refuses-to-work.zip)
Config: [master_config.zip](https://github.com/pytroll/posttroll/files/547659/master_config.zip)

**Comment by ch-k** [comment]
This fix seems to solve the issues. We have no related incidents since we've rolled out the patch.

**Comment by mraspaud** [comment]
@ch-k great ! I'm closing the issue then, feel free to reopen if needed.
